import { Language } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    title: 'AI Tutor Pro',
    tutor: 'Tutor',
    dashboard: 'Dashboard',
    selectSubject: 'Select a Subject',
    math: 'Mathematics',
    physics: 'Physics',
    history: 'History',
    languageArts: 'Language Arts',
    customSubjectPlaceholder: 'Or type a custom subject...',
    startLearning: 'Start Learning',
    welcomeMessage: 'Welcome! I am your personal AI Tutor. Please select a subject to begin.',
    listening: 'Listening...',
    connecting: 'Connecting to AI...',
    startSpeaking: 'Tap the mic and start speaking',
    typeMessage: 'Type your message...',
    progressTitle: 'My Progress',
    noProgress: 'No progress tracked yet. Complete a session to see your summary here.',
    sessionSummary: 'Session Summary',
    endSession: 'End Lesson & See Summary',
    newSession: 'Start New Session',
    generatingSummary: 'Generating lesson summary...',
    language: 'Language',
    startQuiz: 'Start Quiz',
    endQuiz: 'End Quiz',
    submitAnswer: 'Submit Answer',
    nextQuestion: 'Next Question',
    generatingQuestion: 'Generating question...',
    score: 'Score',
    selectLevel: 'Select Your Level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    generatingLessons: 'Generating a personalized lesson plan...',
    selectLesson: 'Select a Lesson to Begin',
    backToSubjects: 'Back to Subjects',
    backToLevels: 'Back to Levels',
    generatingObjectives: 'Preparing your lesson objectives...',
    lessonsCompleted: 'Lessons Completed',
    changeSubject: 'Change Subject & Level',
    performanceTrendDefault: "This is your first lesson on this topic. Let's set a great baseline!",
    performanceTrendMessage: "Here is your past performance on this subject:\n",
    performanceChart: 'Performance Over Time',
    filterBySubject: 'Filter by Subject',
    filterByLevel: 'Filter by Level',
    allSubjects: 'All Subjects',
    allLevels: 'All Levels',
    myBadges: 'My Badges',
    continueLearning: 'Continue Learning',
    editProfile: 'Edit Profile',
    save: 'Save',
    hello: 'Hello',
    badge5Lessons: 'Dedicated Learner',
    badge5LessonsDesc: 'Completed 5 lessons.',
    badgePerfectScore: 'Top Achiever',
    badgePerfectScoreDesc: 'Achieved a perfect score in a quiz.',
    badgeMultiSubject: 'Polymath',
    badgeMultiSubjectDesc: 'Studied more than one subject.',
    noScoreData: 'No quiz score data available for this selection.',
    welcomeTitle: 'Welcome to AI Tutor Pro',
    startLearningBtn: 'Start Learning',
    viewDashboardBtn: 'View Dashboard',
    settingsBtn: 'Settings',
    settingsTitle: 'Settings',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    close: 'Close',
  },
  [Language.AR]: {
    title: 'المعلم الذكي برو',
    tutor: 'المعلم',
    dashboard: 'لوحة التحكم',
    selectSubject: 'اختر موضوعًا',
    math: 'الرياضيات',
    physics: 'الفيزياء',
    history: 'التاريخ',
    languageArts: 'فنون اللغة',
    customSubjectPlaceholder: 'أو اكتب موضوعًا مخصصًا...',
    startLearning: 'ابدأ التعلم',
    welcomeMessage: 'أهلاً بك! أنا معلمك الذكي الشخصي. يرجى اختيار موضوع للبدء.',
    listening: 'يستمع...',
    connecting: 'جاري الاتصال بالذكاء الاصطناعي...',
    startSpeaking: 'اضغط على الميكروفون وابدأ التحدث',
    typeMessage: 'اكتب رسالتك...',
    progressTitle: 'تقدمي',
    noProgress: 'لم يتم تتبع أي تقدم بعد. أكمل جلسة لرؤية ملخصك هنا.',
    sessionSummary: 'ملخص الجلسة',
    endSession: 'إنهاء الدرس ورؤية الملخص',
    newSession: 'بدء جلسة جديدة',
    generatingSummary: 'جاري إنشاء ملخص الدرس...',
    language: 'اللغة',
    startQuiz: 'ابدأ الاختبار',
    endQuiz: 'إنهاء الاختبار',
    submitAnswer: 'إرسال الإجابة',
    nextQuestion: 'السؤال التالي',
    generatingQuestion: 'جاري إنشاء السؤال...',
    score: 'النتيجة',
    selectLevel: 'اختر مستواك',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    generatingLessons: 'جاري إنشاء خطة دروس مخصصة...',
    selectLesson: 'اختر درسًا للبدء',
    backToSubjects: 'العودة إلى المواضيع',
    backToLevels: 'العودة إلى المستويات',
    generatingObjectives: 'جاري تحضير أهداف الدرس...',
    lessonsCompleted: 'الدروس المكتملة',
    changeSubject: 'تغيير الموضوع والمستوى',
    performanceTrendDefault: 'هذا هو درسك الأول في هذا الموضوع. فلنضع أساسًا رائعًا!',
    performanceTrendMessage: 'هذا هو أداؤك السابق في هذا الموضوع:\n',
    performanceChart: 'الأداء مع مرور الوقت',
    filterBySubject: 'التصفية حسب الموضوع',
    filterByLevel: 'التصفية حسب المستوى',
    allSubjects: 'كل المواضيع',
    allLevels: 'كل المستويات',
    myBadges: 'أوسمتي',
    continueLearning: 'متابعة التعلم',
    editProfile: 'تعديل الملف الشخصي',
    save: 'حفظ',
    hello: 'مرحباً',
    badge5Lessons: 'متعلم متفانٍ',
    badge5LessonsDesc: 'أكملت 5 دروس.',
    badgePerfectScore: 'متفوق',
    badgePerfectScoreDesc: 'حققت درجة كاملة في اختبار.',
    badgeMultiSubject: 'واسع المعرفة',
    badgeMultiSubjectDesc: 'درست أكثر من موضوع واحد.',
    noScoreData: 'لا توجد بيانات درجات متاحة لهذا التحديد.',
    welcomeTitle: 'أهلاً بك في المعلم الذكي برو',
    startLearningBtn: 'ابدأ التعلم',
    viewDashboardBtn: 'عرض لوحة التحكم',
    settingsBtn: 'الإعدادات',
    settingsTitle: 'الإعدادات',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    close: 'إغلاق',
  },
};

export const MOCKED_SUBJECTS = ['math', 'physics', 'history', 'languageArts'];

export const LEVELS = ['beginner', 'intermediate', 'advanced'];